//ダックの状態
export enum DuckState {
    CHILD_ENTER = "CHILD_ENTER",
    CHILD_DETECTION = "CHILD_DETECTION",
    SENIOR_ENTER = "SENIOR_ENTER",
    SENIOR_DETECTION = "SENIOR_DETECTION",
    SLEEP = "SLEEP",
}