import 'core-js/stable';
import 'regenerator-runtime/runtime';
import type { Metadata } from "next";
import { Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";

const zenMaru = Zen_Maru_Gothic({weight: '900', subsets: ["latin"]});

export const metadata: Metadata = {
  title: "おふろみまもりだっく",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="manifest" href="/manifest.json"/>
      <link rel="apple-touch-icon" href="/icon512_maskable.png"></link>
      <meta name="theme-color" content="#b8e986"/>
    </head>
    <body className={zenMaru.className}>{children}</body>
    </html>
  );
}

